apiVersion: batch/v1
kind: CronJob
metadata:
  name: ngnxcheck
  namespace: homework2
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl 10.132.0.2:30007
          restartPolicy: OnFailure