apiVersion: batch/v1
kind: Job
metadata:
 name: nodeport
 namespace: homework2
spec:
 template:
   spec:
     containers:
     - name: curl
       image: curlimages/curl
       command: ['curl', '10.132.0.2:30007']
     restartPolicy: OnFailure
 backoffLimit: 4