apiVersion: batch/v1
kind: Job
metadata:
 name: curlclusterip
 namespace: homework2
spec:
 template:
   spec:
     containers:
     - name: curl
       image: curlimages/curl
       command: ['curl', '10.104.127.140']
     restartPolicy: OnFailure
 backoffLimit: 4